### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PushkarOP** [ipad54/INether#10]
Maybe add generator also like 1.16 then it will be so good

**Comment by ipad54** [comment]
For vanilla generation please use Minecraft Java edition and FastChunkPreGenerator plugin

**Comment by hausemaster3734** [comment]
> Maybe add generator also like 1.16 then it will be so good

This is a plugin with the implementation of new blocks from 1.16 updates, and not creating new generator, or something.

**Comment by jibixyt** [comment]
> For vanilla generation please use Minecraft Java edition and FastChunkPreGenerator plugin

That doesn't work, because you can't use +1.13 worlds in PMMP :(

**Comment by ipad54** [comment]
https://github.com/PowerNukkit/Java2Nukkit-World-Converter

**Comment by ipad54** [comment]
This tool works fine on 1.16.5
