### ISSUE TITLE
Blackstone 

### ISSUE THREAD

**Issue by Steellgold** [ipad54/INether#13]
The Blackstone block is not created but these variants are.

![image](https://user-images.githubusercontent.com/51505384/151695080-c7a33cbc-556d-4453-9833-b7d04bdcfb7f.png)

Even with the give order I can't get it

**Comment by Steellgold** [comment]
And do you know why some blocks like basalt or some types of wood logs don't turn in the right direction from where it is placed?

**Comment by ipad54** [comment]
Thanks for report, this will be fixed in the next update

**Comment by Steellgold** [comment]
And it is when 👀 (I'm not in a hurry)

**Comment by ipad54** [comment]
Today or Tomorrow

**Comment by Steellgold** [comment]
It's you Flash ? omygad Barry Alen is real :joy:

**Comment by ipad54** [comment]
Fixed by https://github.com/ipad54/INether/commit/842703a51a6470c4e8b775c2c827484c71110f77

**Comment by Steellgold** [comment]
Wow that was fast, but are you sure the blackstone is in the creative inventory? because I don't see it only these variants

**Comment by ipad54** [comment]
![Uploading Screenshot_20220130_150333_com.mojang.minecraftpe.jpg…]()

**Comment by Steellgold** [comment]
Image not load
![image](https://user-images.githubusercontent.com/51505384/151698857-9ef6e207-3a40-4490-b183-b4b13d385e79.png)

**Comment by Steellgold** [comment]
And another bug 👀 the woods that have the same face (I don't know what they are called in English) also have no rotation
https://youtu.be/0ntIyKlMWM4

**Comment by ipad54** [comment]
Oopps, i forgot to add some blackstone variants

**Comment by Steellgold** [comment]
Is blackstone not show in creative inv (only /give) the variants gold and sculted is good

![image](https://user-images.githubusercontent.com/51505384/151699014-2156dab4-a7ac-4c29-add9-f260f5e3bacb.png)

**Comment by Steellgold** [comment]
![image](https://user-images.githubusercontent.com/51505384/151699030-122c0c04-f247-43ea-89d2-9f80c1f41531.png)

**Comment by Steellgold** [comment]
And suggestion: add Crimson and Warped Sign
They are ugly but at least there are all types of panels :')

**Comment by ipad54** [comment]
Blackstone contains in Creative Inventory, but only in search menu, 
![Screenshot_20220130_151328_com mojang minecraftpe](https://user-images.githubusercontent.com/63200545/151699176-8f4de04a-a085-4ab4-a0f9-8b0421272464.jpg)

Idk why

**Comment by Steellgold** [comment]
Hmmm okay it's weird

**Comment by Steellgold** [comment]
If you plan to add 100% of the 1.16 don't forget the tiles, walls, items, the shiny frame item 

Fin.., these are just suggestions :) I admire the effort you put into this plugin, keep it up!

**Comment by ipad54** [comment]
Glowing frame was added in 1.17

**Comment by Steellgold** [comment]
> Glowing frame was added in 1.17

I was sure it was added in 1.16 😂

**Comment by Steellgold** [comment]
@ipad54 I tried to add the Smooth Basalt but unfortunately we can't
![image](https://user-images.githubusercontent.com/51505384/151700828-b581f6e0-1be3-4dfc-a4cc-b8b25bd58ac5.png)

**Comment by ipad54** [comment]
We can; ItemId or BlockId is incorrect

**Comment by Steellgold** [comment]
Humm ok I'll look for it, if potentially you add it in a next commit I'll go see if I got it right ahah

**Comment by ipad54** [comment]
Try now rotation with https://github.com/ipad54/INether/commit/c64d3c2316cae05acc4fd8eebd0fb1ac66b90d6f

> And another bug 👀 the woods that have the same face (I don't know what they are called in English) also have no rotation https://youtu.be/0ntIyKlMWM4

**Comment by Steellgold** [comment]
It's work fine 
Can you try to add the smooth basalt? I couldn't add it unfortunately

**Comment by ipad54** [comment]
I will add it soon

**Comment by ipad54** [comment]
Done

**Comment by ipad54** [comment]
Smooth basalt was added in 1.17

**Comment by ipad54** [comment]
![Screenshot_109](https://user-images.githubusercontent.com/63200545/151705747-d337802e-d903-4787-a87c-fdc14bb7c851.png)
