### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by Steellgold** [ipad54/INether#15]
[src/ipad54/netherblocks/items/FlintAndSteel.php](https://github.com/ipad54/INether/blob/master/src/ipad54/netherblocks/items/FlintAndSteel.php#L25)

https://user-images.githubusercontent.com/51505384/152035690-12e4bd64-d461-48dc-be6f-3f166e413071.mp4

When you right click it, it creates a new block 😂 isn't it a bit cheat ? 

I suggest:
```PHP
$world->setBlock($blockReplace->getPosition(), VanillaBlocks::FIRE());
```

**Comment by ipad54** [comment]
LMAO, I can’t reproduce this

**Comment by ipad54** [comment]
https://youtu.be/_aLpyzQ-VhE
