### ISSUE TITLE
Question: Custom Buttons

### ISSUE THREAD

**Issue by Steellgold** [ipad54/INether#16]
Hello how are you?!

I'm implementing buttons and tiles, no problem with the tiles but the buttons... hmm don't work properly.

When I put them on any block no problem only... when you press them either they change position or it does this (see video) would you know why?

```PHP
self::registerBlock(new StoneButton(new BlockIdentifier(VanillaBlockIds::POLISHED_BLACKSTONE_BUTTON,0,VanillaItemsIds::POLISHED_BLACKSTONE_BUTTON),"Polished Blackstone Button",new BBI(1, BlockToolType::AXE, 0, 6)));
self::registerBlock(new WoodenButton(new BlockIdentifier(VanillaBlockIds::CRIMSON_BUTTON,0,VanillaItemsIds::CRIMSON_BUTTON),"Crimson Button",new BBI(3, BlockToolType::AXE, 0, 6)));
self::registerBlock(new WoodenButton(new BlockIdentifier(VanillaBlockIds::WARPED_BUTTON,0,VanillaItemsIds::WARPED_BUTTON),"Warped Button",new BBI(3, BlockToolType::AXE, 0, 6)));
```

IDS:
Items:
```PHP
public const POLISHED_BLACKSTONE_BUTTON = -296;
public const CRIMSON_BUTTON = -260;
public const WARPED_BUTTON = -261;
```
Blocks:
```PHP
public const POLISHED_BLACKSTONE_BUTTON = 551;
public const CRIMSON_BUTTON = 515;
public const WARPED_BUTTON = 516;
```

And yes some classes are not the same as yours I re-advanced your plugin with some modification to add blocks of versions >1.16 so I changed a little I hope you do not blame me ^^

If you want I can fork you a version and you create a 1.17 plugin

https://user-images.githubusercontent.com/51505384/152307157-08e136c6-7445-4fcb-8efa-13d43316497b.mp4

**Comment by ipad54** [comment]
Buttons & Slab's had another metadata;

I already create 1.17 plugin, but it stills incomplete

**Comment by ipad54** [comment]
I dont implement button's & Slab's because I don't know what their metadata is

**Comment by Steellgold** [comment]
I found this (down) in [link](https://minecraft.fandom.com/wiki/Button)
![image](https://user-images.githubusercontent.com/51505384/152309540-c1b0b4b6-7075-49e3-84cf-e7201ae74642.png)

I tried to add in the variable "variant" but it gives me errors, and other attempts that also gave nothing unless to define metadata is somewhere else, and in this case I would like to know where if possible

**Comment by ipad54** [comment]
In PowerNukkit these blocks works fine, but i don't know where PowerNukkit store these metadata

**Comment by Steellgold** [comment]
I just took a look, the power nukkit buttons work with directions so from 1 to 5 and if pressed normal on a block 0 or 1 

https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/block/BlockButton.java#L199-L201
https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/block/BlockButton.java#L172-L174
https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/block/BlockButton.java#L179-L181
https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/block/BlockButton.java#L86
https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/block/BlockButton.java#L53-L55

![image](https://user-images.githubusercontent.com/51505384/152310570-0558c31d-edb4-4578-9cd8-bf76fd9042ac.png)

**Comment by ipad54** [comment]
Hmm, i check this on PM later

**Comment by Steellgold** [comment]
A small question, I noticed you were testing on phone, do you also develop on phone ? if its the case I owe you some respect 😲 I won't have the courage to do it on phone 😂

**Comment by ipad54** [comment]
I develop on my PC, but i developed on phone 7 months ago...

**Comment by Steellgold** [comment]
Ohh okay

**Comment by Steellgold** [comment]
All in all I can't wait to see your version 1.17 or even 1.18 because some blocks I can't add at all and others are easy

**Comment by ipad54** [comment]
Slab's works fin
![Screenshot_112](https://user-images.githubusercontent.com/63200545/152325574-3833e46f-68f4-4047-b9c6-49005b3bdb4b.png)
e

**Comment by Steellgold** [comment]
Ohh nicee, i wait your commits ah ah :')

**Comment by Steellgold** [comment]
Wait, omg you have implemented nether biomes ? That's what I'm trying to do now with the base of jason's NativeDimensions plugin 😲 but I can't do it

**Comment by ipad54** [comment]
![Screenshot_113](https://user-images.githubusercontent.com/63200545/152326843-41a4037e-060d-4f47-a9cc-99d658448191.png)

**Comment by Steellgold** [comment]
OOH holy shit, this is amazing, did you do this?

**Comment by Steellgold** [comment]
So many things I've been trying to do for the last 2-3 months without success 😂 could you show me some examples of how to make a biome if you don't mind, otherwise I will continue to break my head

**Comment by ipad54** [comment]
https://github.com/PowerNukkit/PowerNukkit/pull/1253

I translate this to PM

**Comment by Steellgold** [comment]
No kidding? well I know what I'm going to do during my next 2 weeks of vacation ah ah

**Comment by Steellgold** [comment]
Thank you for the tip!

**Comment by ipad54** [comment]
> No kidding? well I know what I'm going to do during my next 2 weeks of vacation ah ah

I translated it in 1.5 days

**Comment by Steellgold** [comment]
Ohh okay, but i'm noob in java 😂

**Comment by Steellgold** [comment]
Have you discord? it's just to know, so if I have some questions I don't have to create useless issues

**Comment by ipad54** [comment]
Глеб#9311

**Comment by Steellgold** [comment]
thanks you 😸
