### ISSUE TITLE
Composter

### ISSUE THREAD

**Issue by max-xoo** [ipad54/INether#17]
Good evening, would it be possible to add the composter plugin inside this plugin? I know it's not implemented in 1.16 but in 1.14, but I think it would be nice.

(it's mostly psychological, personally I like it when there are not too many plugins (and I'm really lazy to enter all this plugin in my core)

**Comment by ipad54** [comment]
https://github.com/ipad54/Composter

**Comment by max-xoo** [comment]
You have not understood

**Comment by ipad54** [comment]
I'm not planning to add blocks below 1.16
