### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YaNIND** [ipad54/INether#18]
Scalfolding functional

**Comment by ipad54** [comment]
Do you read this?
![Screenshot_20220214_202006](https://user-images.githubusercontent.com/63200545/153914093-4094f479-d54c-40b9-b31a-86c89b04bb36.jpg)


This plugin aims to implement all blocks and items that were added in 1.16 (Minecraft Nether Update)

**Comment by YaNIND** [comment]
1.16 is have scalfolding

**Comment by ipad54** [comment]
You misunderstood, this plugin adds blocks/items that were added in Minecraft Nether Update. 

https://minecraft.fandom.com/wiki/Bedrock_Edition_1.16.0
