### ISSUE TITLE
Netherite armor parts cannot be placed in item frames

### ISSUE THREAD

**Issue by MrBlasyMSK** [ipad54/INether#20]
https://user-images.githubusercontent.com/85447029/162836263-42468dbb-7769-42ed-b37c-99c5c0861c00.mp4

In the code there should be some part where if you are looking at an item frame or an armorstand, put it on it before yourself, i guess it can be better

**Comment by ipad54** [comment]
Weird, on my test server it's works fine

https://youtu.be/vHAQA_CEYqU

**Comment by MrBlasyMSK** [comment]
> Weird, on my test server it's works fine
> 
> https://youtu.be/vHAQA_CEYqU

The video you show is from a phone, if you try it on pc you will see that it does not let you put the armor

**Comment by MrBlasyMSK** [comment]
Ah no, it doesnt work on my phone

**Comment by MrBlasyMSK** [comment]
Its a "PerWorldPlayer" plugin error

**Comment by hausemaster3734** [comment]
hmhmhmhmmm...
