### ISSUE TITLE
Updated Blocks

### ISSUE THREAD

**Issue by galaxytwenty** [ipad54/INether#26]
in PM5 all those block i have Placed with INether are UpdatedBlocks

**Comment by galaxytwenty** [comment]
any help ?

**Comment by ipad54** [comment]
Hi, I don't see the point in updating this plugin to pm5, because most blocks from INether are already implemented in pm5.

**Comment by galaxytwenty** [comment]
yes, i mean when i put my PM4 World into an PM5 world, then ALL blocks i have PLaced With INether Now Updated Blocks.
and my map turning into an Updatedland xD.

**Comment by ipad54** [comment]
You need to register the blocks in \pocketmine\data\bedrock\block\convert\BlockStateToBlockObjectDeserializer and \pocketmine\data\bedrock\block\convert\BlockObjectToBlockStateSerializer

**Comment by galaxytwenty** [comment]
can u give us an Converter Plugin `?

**Comment by ipad54** [comment]
I don't have a converter.

**Comment by ipad54** [comment]
Does nether wood turn into an update block?

**Comment by galaxytwenty** [comment]
Yes

**Comment by ipad54** [comment]
This is very sad news :(

This is due to the fact that the PM4 world is saved in 1.12 format using the legacy block ids. Because of this, pm5 does not recognize new blocks, because they are saved in the old format. This means that it will be impossible to convert the blocks(

**Comment by galaxytwenty** [comment]
Have you check this ?
https://github.com/pmmp/PocketMine-MP/commit/56e6a5564534bf6b0930556b2d1c5521561560c6

**Comment by galaxytwenty** [comment]
there is a way.... but i dont understand this way

**Comment by ipad54** [comment]
Hm, this might help. I will try to make a converter one of these days

**Comment by galaxytwenty** [comment]
Special Thanks
