### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by XxGalaxy300** [ipad54/INether#28]
Hello! I have a question how can i download the plugin? I cant find a download link!

**Comment by ipad54** [comment]
Just download it from source and then build it to phar using some sites (like phar.scer.io) or just run it from source using the DevTools plugin.

**Comment by XxGalaxy300** [comment]
Where is the source?

**Comment by ipad54** [comment]
Just click Code -> Download Zip

**Comment by XxGalaxy300** [comment]
Okay thx

**Comment by XxGalaxy300** [comment]
Doesn't work.![Screenshot_20230219-171905_Brave.jpg](https://user-images.githubusercontent.com/125708368/219960648-b6ef1b87-c9cd-43e0-a033-e3f305dae731.jpg)

![Screenshot_20230219-171900_Brave.jpg](https://user-images.githubusercontent.com/125708368/219960647-41db8b6f-88e1-4477-9ba8-ca21093fc573.jpg)

**Comment by XxGalaxy300** [comment]
Can you send me the link please
