### ISSUE TITLE
Bug PM 4.16

### ISSUE THREAD

**Issue by nebotLol** [ipad54/INether#29]
Error: file_get_contents(phar:///root/pm/PocketMine-MP.phar/vendor/pocketmine/bedrock-data/block_id_map.json): Failed to open stream: phar error: "vendor/pocketmine/bedrock-data/block_id_map.json" is not a file in phar "/root/pm/PocketMine-MP.phar"
File: plugins/INether-master/src/ipad54/netherblocks/Main
Line: 140
Type: ErrorException
Backtrace:
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[241] file_get_contents(phar:///root/pm/PocketMine-MP.phar/vendor/pocketmine/bedrock-d, string[64] /root/pm/plugins/INether-master/src/ipad54/netherblocks/Main.php, int 140)
#1 plugins/INether-master/src/ipad54/netherblocks/Main(140): file_get_contents(string[83] phar:///root/pm/PocketMine-MP.phar/vendor/pocketmine/bedrock-data/block_id_map.j)
#2 plugins/INether-master/src/ipad54/netherblocks/Main(103): ipad54\netherblocks\Main::initializeRuntimeIds()
#3 pmsrc/src/plugin/PluginBase(76): ipad54\netherblocks\Main->onLoad()
#4 pmsrc/src/plugin/PluginManager(216): pocketmine\plugin\PluginBase->__construct(object DevTools\FolderPluginLoader#22123, object pocketmine\Server#12, object pocketmine\plugin\PluginDescription#22297, string[28] /root/pm/plugin_data/INether, string[31] /root/pm/plugins/INether-master, object pocketmine\plugin\DiskResourceProvider#23067)
#5 pmsrc/src/plugin/PluginManager(368): pocketmine\plugin\PluginManager->internalLoadPlugin(string[31] /root/pm/plugins/INether-master, object DevTools\FolderPluginLoader#22123, object pocketmine\plugin\PluginDescription#22297)
#6 pmsrc/src/Server(1008): pocketmine\plugin\PluginManager->loadPlugins(string[17] /root/pm/plugins/, int 0)
#7 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[9] /root/pm/, string[17] /root/pm/plugins/)
#8 pmsrc/src/PocketMine(362): pocketmine\server()
#9 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)

**Comment by skyss0fly** [comment]
the error seen here is because when pocket mine updated to 4.16.0 it updated the file bedrockdata, instead of block_id_map.json, it got replaced to block_legacy_id_map. which basically means the plugin is saying there is no id map, so what needs to change is the directory, I believe.

**Comment by ipad54** [comment]
Fixed by https://github.com/ipad54/INether/commit/c3f4d21ab51f1835c615c2b8f8db5cee2e1b6604
