### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by UnknownNull** [ipad54/INether#34]
PM 4.17.1 and 4.18.0

**Comment by ipad54** [comment]
Already updated, download newest version from poggit or source

**Comment by UnknownNull** [comment]
Do you provide a version for PM-NG?

**Comment by ipad54** [comment]
No, but to make it work on NG fork, you just need register mappings for all protocols

**Comment by UnknownNull** [comment]
how register mappings for all protocols?

**Comment by ipad54** [comment]
Just iterate through all protocols using foreach and register mappings for them, like here:

https://github.com/ipad54/INether/blob/master/src/ipad54/netherblocks/Main.php#L141-L152

**Comment by UnknownNull** [comment]
![image](https://user-images.githubusercontent.com/91208232/227778975-4fa1bc8c-ce73-44a1-adbd-d5fc8d07d712.png)
I got confused...
