### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by galaxytwenty** [ipad54/INether#4]
Crimson & Warped Doors !.

		$warpeddoor = (new warpedDoor(new BID(500, 0, 756), new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
		self::registerBlockGlobally($warpeddoor);
		
		$crimsondoor = (new Door(new BID(499, 0, 755),"crimson_door", new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
		BlockFactory::getInstance()->register($crimsondoor);

Thanks :)

**Comment by ipad54** [comment]
Thank you, but what do you mean?

**Comment by galaxytwenty** [comment]
I mean Pls add The Doors Crimson & warped.

and i cant put the wood´s in furnance!.

Greetzs

**Comment by ipad54** [comment]
Nether wood can't be used like fuel in vanilla.

Doors already implemented, hmm, i check this

**Comment by galaxytwenty** [comment]
oh Okay, i have no doors from crimson or warped.

**Comment by ipad54** [comment]
Fixed by https://github.com/ipad54/INether/commit/3355941cb6b4509f36ddb4bfd17dfbfd0bd865b9

**Comment by galaxytwenty** [comment]
yeah, nice, but cant place 2 doors like [ ]

the doors placing is like [ [

Greetz

**Comment by galaxytwenty** [comment]
meaning cannot using doubledoors in the right way

**Comment by galaxytwenty** [comment]
![door](https://user-images.githubusercontent.com/79281788/145711530-6a909a33-0370-4a04-ae13-680611107dbf.PNG)

**Comment by galaxytwenty** [comment]
normal doors looks like :
![door2](https://user-images.githubusercontent.com/79281788/145711546-dc7af6ec-2b14-4858-b871-e51ce96c5c07.PNG)

**Comment by hausemaster3734** [comment]
> Crimson & Warped Doors !.
> 
> ```
> 	$warpeddoor = (new warpedDoor(new BID(500, 0, 756), new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
> 	self::registerBlockGlobally($warpeddoor);
> 	
> 	$crimsondoor = (new Door(new BID(499, 0, 755),"crimson_door", new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
> 	BlockFactory::getInstance()->register($crimsondoor);
> ```
> 
> Thanks :)



> Crimson & Warped Doors !.
> 
> ```
> 	$warpeddoor = (new warpedDoor(new BID(500, 0, 756), new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
> 	self::registerBlockGlobally($warpeddoor);
> 	
> 	$crimsondoor = (new Door(new BID(499, 0, 755),"crimson_door", new BlockBreakInfo(0.5, BlockToolType::AXE, 0)));
> 	BlockFactory::getInstance()->register($crimsondoor);
> ```
> 
> Thanks :)

Where did you get this code from?Can you please drop the link here?

**Comment by galaxytwenty** [comment]
have you got fixed the bug ?

**Comment by hausemaster3734** [comment]
> have you got fixed the bug ?

Doors in PM is something strange...
