### ISSUE TITLE
SoulFire Bug

### ISSUE THREAD

**Issue by galaxytwenty** [ipad54/INether#7]
SoulFire cant disapers.

plce soulsand or soulsoil and tipped it with FlintandSteel

then tip the SoulFire to disaper it.

then go over the soulsand or soulsoil, and without fire on this place gets burned !.

Greetz :)

**Comment by hausemaster3734** [comment]
ik this bug lol

**Comment by ipad54** [comment]
Thank you for report, i'm fix this very soon

**Comment by ipad54** [comment]
Try now with https://github.com/ipad54/INether/commit/1c6074aa99f5ef0a4ec4d88722fbe4a6cf924f31

**Comment by ipad54** [comment]
Fixed by https://github.com/ipad54/INether/commit/1c6074aa99f5ef0a4ec4d88722fbe4a6cf924f31
