### ISSUE TITLE
Another suggestion

### ISSUE THREAD

**Issue by galaxytwenty** [ipad54/INether#8]
Can u add cauldron and lava cauldron.

so that i can filled water in cauldron and dye my lether armor ?.

Thanks and NICE work man.

Greetz

**Comment by galaxytwenty** [comment]
Did you Know how it works?,.

maybe i can help.

**Comment by ipad54** [comment]
This plugin implements the functionality of items and blocks that were added in 1.16, Cauldron is not included in this list.

But I will make a Cauldron plugin very soon
